version: '3.1'

services:
  postgresql:
    container_name: postregsql_myth
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=mythUser
      - POSTGRES_PASSWORD=mythPassword
      - POSTGRES_DB=myth
    networks:
      - mythapp-network
    ports:
      - 5434:5432
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
  mongodb:
    container_name: mongodb_myth
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "localMyth"
      MONGO_INITDB_ROOT_PASSWORD: "localMyth"
    networks:
      - mythapp-network
networks:
  mythapp-network: